ALTER TABLE "WorkerProfile" ADD COLUMN IF NOT EXISTS "canAssignBonusCredits" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "WorkerProfile" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
