/**
 * Statická query banka pro YouTube channel discovery.
 * Klíč = slug ContentSourceCategory.
 */
export const YOUTUBE_DISCOVERY_QUERY_BANK: Record<string, string[]> = {
  makleri: [
    'realitní makléř',
    'realitní makléř Česko',
    'realitní makléř Praha',
    'realitní makléř Brno',
    'realitní makléř Ostrava',
    'realitní makléř Plzeň',
    'realitní makléř Pardubice',
    'realitní makléř Hradec Králové',
    'realitní makléř Olomouc',
    'realitní makléř Liberec',
    'prodej nemovitosti',
    'jak prodat byt',
    'jak prodat dům',
    'prohlídka nemovitosti',
    'realitní tipy',
    'realitní trh',
    'reality Česko',
    'realitní kancelář',
    'realitní makléř Slovensko',
    'koupě bytu tipy',
  ],
  'realitni-kancelare': [
    'realitní kancelář',
    'realitní agentura',
    'realitní kancelář Praha',
    'realitní kancelář Brno',
    'RK reality',
    'prodej nemovitostí česko',
    'realitní služby',
    'realitní poradenství',
  ],
  'developerske-projekty': [
    'developer nemovitosti',
    'developerský projekt',
    'novostavby',
    'nové byty',
    'developerské projekty Praha',
    'developerské projekty Brno',
    'výstavba bytů',
    'rezidenční projekt',
    'novostavba rodinný dům',
  ],
  'stavebni-firmy': [
    'stavební firma',
    'stavba domu',
    'stavba rodinného domu',
    'hrubá stavba',
    'základy domu',
    'zateplení domu',
    'fasáda domu',
    'střecha rekonstrukce',
    'betonování',
    'zdění domu',
    'dřevostavba',
    'modulární dům',
    'pasivní dům',
    'stavebnictví česko',
    'fotovoltaika dům',
    'tepelné čerpadlo',
    'vytápění domu',
    'solární elektrárna rodinný dům',
    'stavební materiály',
    'okna dveře montáž',
    'zahrada stavba',
    'chytrá domácnost',
  ],
  remeslnici: [
    'zedník',
    'tesař',
    'klempíř',
    'pokrývač',
    'elektrikář rekonstrukce',
    'instalatér',
    'topenář',
    'sádrokartonář',
    'obkladač',
    'podlahář',
    'malíř pokoj',
    'truhlář na míru',
    'rekonstrukce koupelny',
    'montáž oken',
    'řemeslník rekonstrukce',
    'kuchyně na míru',
  ],
  architektura: [
    'architekt dům',
    'návrh domu',
    'architektura bydlení',
    'projekt domu',
    'stavební projekt rodinný dům',
    'architekt Praha',
  ],
  interiery: [
    'interiérový design',
    'návrh interiéru',
    'kuchyně inspirace',
    'koupelna design',
    'rekonstrukce interiéru',
    'nábytek na míru',
    'chytrá domácnost',
    'bytový design',
  ],
  rekonstrukce: [
    'rekonstrukce bytu',
    'rekonstrukce domu',
    'přestavba bytu',
    'rekonstrukce koupelny',
    'rekonstrukce kuchyně',
    'kompletní rekonstrukce',
    'rekonstrukce panelového bytu',
  ],
  'hypoteky-finance': [
    'hypotéka',
    'hypoteční poradce',
    'hypoteční sazby',
    'financování bydlení',
    'refinancování hypotéky',
    'hypotéka na dům',
    'hypotéka na byt',
    'investiční hypotéka',
    'úvěr na bydlení',
  ],
  investice: [
    'investice do nemovitostí',
    'pronájem bytu',
    'realitní investice',
    'koupě na pronájem',
    'výnosnost nemovitosti',
    'flip nemovitost',
  ],
  'pravo-legislativa': [
    'realitní právo',
    'kupní smlouva nemovitost',
    'legislativa bydlení',
    'katastr nemovitostí',
    'převod nemovitosti',
  ],
  bydleni: [
    'bydlení tipy',
    'první byt',
    'nájem vs koupě',
    'bydlení pro mladé',
    'levné bydlení',
    'rekolaudace',
  ],
  'ubytovani-cestovani': [
    'ubytování airbnb',
    'rekreační pronájem',
    'apartmán pronájem',
    'hotel investice',
    'krátkodobý pronájem',
    'reality zahraničí',
  ],
  'technologie-pro-reality': [
    'proptech',
    'technologie reality',
    'digitalizace realit',
    'virtuální prohlídka nemovitost',
  ],
  ostatni: [
    'realitní trh česko',
    'ceny nemovitostí',
    'novinky reality',
    'trh s nemovitostmi',
    'nemovitosti Slovensko',
  ],
};

/** Vrátí rotovaný výběr dotazů pro kategorii. */
export function pickDiscoveryQueries(
  categorySlug: string,
  maxQueries: number,
  rotationOffset: number,
): string[] {
  const bank =
    YOUTUBE_DISCOVERY_QUERY_BANK[categorySlug] ?? YOUTUBE_DISCOVERY_QUERY_BANK.ostatni;
  if (!bank.length || maxQueries <= 0) return [];
  const start = rotationOffset % bank.length;
  const picked: string[] = [];
  for (let i = 0; i < bank.length && picked.length < maxQueries; i++) {
    const q = bank[(start + i) % bank.length];
    if (!picked.includes(q)) picked.push(q);
  }
  return picked;
}
