ALTER TYPE "CompanyReviewCompanyNotificationStatus" ADD VALUE IF NOT EXISTS 'WAITING_FOR_REVIEW_APPROVAL';
ALTER TYPE "CompanyReviewCompanyNotificationStatus" ADD VALUE IF NOT EXISTS 'ALREADY_SENT';

ALTER TYPE "CompanyAuditAction" ADD VALUE IF NOT EXISTS 'CLAIM_REQUEST_APPROVED';
ALTER TYPE "CompanyAuditAction" ADD VALUE IF NOT EXISTS 'COMPANY_EMAIL_APPROVED';
ALTER TYPE "CompanyAuditAction" ADD VALUE IF NOT EXISTS 'COMPANY_EMAIL_ATTACHED';
ALTER TYPE "CompanyAuditAction" ADD VALUE IF NOT EXISTS 'COMPANY_REVIEW_NOTIFICATION_QUEUED';
ALTER TYPE "CompanyAuditAction" ADD VALUE IF NOT EXISTS 'COMPANY_REVIEW_NOTIFICATION_SENT';
ALTER TYPE "CompanyAuditAction" ADD VALUE IF NOT EXISTS 'COMPANY_REVIEW_NOTIFICATION_FAILED';

ALTER TABLE "CompanyClaimRequest" ADD COLUMN IF NOT EXISTS "approvedByAdminId" TEXT;
ALTER TABLE "CompanyClaimRequest" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
ALTER TABLE "CompanyClaimRequest" ADD COLUMN IF NOT EXISTS "linkedReviewId" TEXT;
ALTER TABLE "CompanyClaimRequest" ADD COLUMN IF NOT EXISTS "companyEmailAttached" BOOLEAN NOT NULL DEFAULT false;
