import type { AccommodationProviderItem } from '../providers/accommodation-provider.interface';

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=80`;

export const DEMO_ACCOMMODATIONS: AccommodationProviderItem[] = [
  {
    externalId: 'demo-hotel-panorama-praha',
    slug: 'hotel-panorama-praha',
    type: 'HOTEL',
    name: 'Hotel Panorama Praha',
    city: 'Praha',
    region: 'Praha',
    address: 'Národní 12, Praha 1',
    latitude: 50.0815,
    longitude: 14.4185,
    stars: 4,
    rating: 9.1,
    reviewCount: 842,
    priceFrom: 2890,
    currency: 'CZK',
    priceUnit: 'PER_NIGHT',
    shortDescription: 'Moderní hotel v centru Prahy s výhledem na město.',
    description:
      'Hotel Panorama Praha nabízí komfortní pokoje, snídani formou bufetu a wellness zónu. Ideální pro city break i obchodní cesty.',
    amenities: ['Wi-Fi', 'Snídaně', 'Parkování', 'Wellness'],
    tags: ['mesto', 'luxusni'],
    photos: [{ url: img('1566073771259-6a8506099945'), alt: 'Hotel Panorama Praha', isCover: true }],
    facilities: [
      { name: 'Wi-Fi', icon: 'wifi' },
      { name: 'Snídaně', icon: 'coffee' },
      { name: 'Parkování', icon: 'car' },
      { name: 'Wellness', icon: 'spa' },
    ],
  },
  {
    externalId: 'demo-wellness-krkonose',
    slug: 'wellness-hotel-krkonose',
    type: 'WELLNESS',
    name: 'Wellness Hotel Krkonoše',
    city: 'Špindlerův Mlýn',
    region: 'Krkonoše',
    latitude: 50.7256,
    longitude: 15.6089,
    stars: 4,
    rating: 9.4,
    reviewCount: 612,
    priceFrom: 3490,
    amenities: ['Wi-Fi', 'Wellness', 'Bazén', 'Parkování'],
    tags: ['hory', 'wellness'],
    photos: [{ url: img('1571896349842-33c89424de2d'), alt: 'Wellness Hotel Krkonoše', isCover: true }],
  },
  {
    externalId: 'demo-apartmany-lipno',
    slug: 'apartmany-lipno-lake',
    type: 'APARTMENT',
    name: 'Apartmány Lipno Lake',
    city: 'Lipno nad Vltavou',
    region: 'Jižní Čechy',
    rating: 9.0,
    reviewCount: 318,
    priceFrom: 2190,
    amenities: ['Wi-Fi', 'Parkování', 'Kuchyň'],
    tags: ['u-vody', 'hory'],
    photos: [{ url: img('1502672265066-763c14014da2'), alt: 'Apartmány Lipno', isCover: true }],
  },
  {
    externalId: 'demo-boutique-brno',
    slug: 'boutique-hotel-brno-centre',
    type: 'HOTEL',
    name: 'Boutique Hotel Brno Centre',
    city: 'Brno',
    region: 'Jihomoravský kraj',
    stars: 4,
    rating: 8.9,
    reviewCount: 445,
    priceFrom: 2390,
    amenities: ['Wi-Fi', 'Snídaně'],
    tags: ['mesto'],
    photos: [{ url: img('1551882547-ff40c63fe5fa'), alt: 'Boutique Hotel Brno', isCover: true }],
  },
  {
    externalId: 'demo-chalupa-beskydy',
    slug: 'chalupa-beskydy',
    type: 'CHALUPA',
    name: 'Chalupa Beskydy',
    city: 'Čeladná',
    region: 'Moravskoslezský kraj',
    rating: 9.6,
    reviewCount: 128,
    priceFrom: 4900,
    priceUnit: 'PER_STAY',
    amenities: ['Wi-Fi', 'Parkování', 'Kuchyň', 'Gril'],
    tags: ['hory'],
    photos: [{ url: img('1449158743715-0acffed1f21b'), alt: 'Chalupa Beskydy', isCover: true }],
  },
  {
    externalId: 'demo-penzion-krumlov',
    slug: 'penzion-u-zamku',
    type: 'PENSION',
    name: 'Penzion U Zámku',
    city: 'Český Krumlov',
    region: 'Jihočeský kraj',
    stars: 3,
    rating: 9.2,
    reviewCount: 267,
    priceFrom: 1790,
    amenities: ['Wi-Fi', 'Snídaně', 'Parkování'],
    tags: ['mesto'],
    photos: [{ url: img('1520250497591-112f2f40a3f4'), alt: 'Penzion U Zámku', isCover: true }],
  },
  {
    externalId: 'demo-spa-karlovy-vary',
    slug: 'luxury-spa-resort-karlovy-vary',
    type: 'LUXURY',
    name: 'Luxury Spa Resort Karlovy Vary',
    city: 'Karlovy Vary',
    region: 'Karlovarský kraj',
    stars: 5,
    rating: 9.5,
    reviewCount: 521,
    priceFrom: 5990,
    amenities: ['Wi-Fi', 'Wellness', 'Bazén', 'Snídaně', 'Parkování'],
    tags: ['wellness', 'luxusni'],
    photos: [{ url: img('1582719508461-905c673771fd'), alt: 'Spa Resort Karlovy Vary', isCover: true }],
  },
  {
    externalId: 'demo-apartman-stare-mesto',
    slug: 'apartman-stare-mesto',
    type: 'APARTMENT',
    name: 'Apartmán Staré Město',
    city: 'Praha',
    region: 'Praha',
    rating: 8.8,
    reviewCount: 203,
    priceFrom: 2690,
    amenities: ['Wi-Fi', 'Kuchyň'],
    tags: ['mesto'],
    photos: [{ url: img('1502672265066-763c14014da2'), alt: 'Apartmán Staré Město', isCover: true }],
  },
  {
    externalId: 'demo-mountain-lodge-jeseniky',
    slug: 'mountain-lodge-jeseniky',
    type: 'CHATA',
    name: 'Mountain Lodge Jeseníky',
    city: 'Jeseníky',
    region: 'Olomoucký kraj',
    rating: 9.3,
    reviewCount: 156,
    priceFrom: 2790,
    amenities: ['Wi-Fi', 'Parkování', 'Sauna'],
    tags: ['hory'],
    photos: [{ url: img('1510797881214-e90cd69245eb'), alt: 'Mountain Lodge Jeseníky', isCover: true }],
  },
  {
    externalId: 'demo-family-resort-morava',
    slug: 'family-resort-jizni-morava',
    type: 'HOTEL',
    name: 'Family Resort jižní Morava',
    city: 'Pasohlávky',
    region: 'Jihomoravský kraj',
    rating: 8.7,
    reviewCount: 389,
    priceFrom: 3190,
    amenities: ['Wi-Fi', 'Bazén', 'Parkování', 'Snídaně'],
    tags: ['u-vody'],
    photos: [{ url: img('1571003123894-1f0594d655b8'), alt: 'Family Resort jižní Morava', isCover: true }],
  },
];

export const DEMO_ACCOMMODATION_SEED_KEY = 'xxrealit-demo-accommodation-v1';
