ALTER TABLE "SeoAiGenerationJob" ADD COLUMN IF NOT EXISTS "skippedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SeoAiGenerationJob" ADD COLUMN IF NOT EXISTS "retriedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SeoAiGenerationJob" ADD COLUMN IF NOT EXISTS "requestCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SeoAiGenerationJob" ADD COLUMN IF NOT EXISTS "successfulRequestCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SeoAiGenerationJob" ADD COLUMN IF NOT EXISTS "failedRequestCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SeoAiGenerationJob" ADD COLUMN IF NOT EXISTS "totalInputTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SeoAiGenerationJob" ADD COLUMN IF NOT EXISTS "totalOutputTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SeoAiGenerationJob" ADD COLUMN IF NOT EXISTS "pauseReason" TEXT;

ALTER TABLE "SeoAiGenerationItem" ADD COLUMN IF NOT EXISTS "localityName" TEXT;
ALTER TABLE "SeoAiGenerationItem" ADD COLUMN IF NOT EXISTS "localitySlug" TEXT;
ALTER TABLE "SeoAiGenerationItem" ADD COLUMN IF NOT EXISTS "offerType" TEXT;
ALTER TABLE "SeoAiGenerationItem" ADD COLUMN IF NOT EXISTS "propertyType" TEXT;
ALTER TABLE "SeoAiGenerationItem" ADD COLUMN IF NOT EXISTS "phase" TEXT;
ALTER TABLE "SeoAiGenerationItem" ADD COLUMN IF NOT EXISTS "httpStatus" INTEGER;
ALTER TABLE "SeoAiGenerationItem" ADD COLUMN IF NOT EXISTS "durationMs" INTEGER;
ALTER TABLE "SeoAiGenerationItem" ADD COLUMN IF NOT EXISTS "warningsJson" JSONB;
ALTER TABLE "SeoAiGenerationItem" ADD COLUMN IF NOT EXISTS "outputPreviewJson" JSONB;
