-- Shorts video top overlay settings on Property
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "overlayText" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "overlayStyle" TEXT NOT NULL DEFAULT 'modern_real_estate';
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "overlayFont" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "overlayColor" TEXT NOT NULL DEFAULT '#FFFFFF';
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "overlayFontSize" INTEGER NOT NULL DEFAULT 48;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "overlayPosition" TEXT NOT NULL DEFAULT 'center';
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "showLogo" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "showOverlayText" BOOLEAN NOT NULL DEFAULT true;
