-- Property seeker role and onboarding fields

ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PROPERTY_SEEKER';

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "marketingConsentWhatsApp" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "marketingConsentEmail" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "consentCreatedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "consentSource" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "shareCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "shareCompletedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "invitedViaWhatsApp" BOOLEAN NOT NULL DEFAULT false;
