export const AI_INFLUENCER_SETTINGS_KEY = 'ai_influencer_settings';

export const AI_INFLUENCER_WORKER_TICK_MS = 5_000;
export const AI_INFLUENCER_WORKER_WATCHDOG_MS = 60_000;
export const AI_INFLUENCER_QUEUE_STALE_MS = 30_000;
export const AI_INFLUENCER_QUEUE_STALLED_MS = 120_000;
export const AI_INFLUENCER_CLAIM_STALE_MS = 120_000;
export const AI_INFLUENCER_VIDEO_AGENT_SUBMIT_STALE_MS = 90_000;
export const AI_INFLUENCER_VIDEO_AGENT_POLL_STALE_MS = 120_000;
export const AI_INFLUENCER_VIDEO_AGENT_SUBMIT_TIMEOUT_MS = 45_000;
export const AI_INFLUENCER_STORAGE_TIMEOUT_MS = 180_000;
export const AI_INFLUENCER_STORAGE_STUCK_MS = 180_000;

export const AI_INFLUENCER_AUTO_TICK_MS = 60_000;

export const DEFAULT_VOICE_COST_PER_1K_CHARS_CZK = 0.18;
export const DEFAULT_AVATAR_COST_PER_SEC_CZK = 0.35;

export const FORBIDDEN_HOOK_PREFIXES = [
  'dobrý den',
  'vítám vás',
  'v dnešním videu',
  'co je nového ve světě realit',
];
