export const EMAIL_CENTER_PERMISSIONS = [
  'EMAIL_CENTER_VIEW',
  'EMAIL_CENTER_MANAGE_SETTINGS',
  'EMAIL_CENTER_MANAGE_SENDERS',
  'EMAIL_CENTER_MANAGE_TEMPLATES',
  'EMAIL_CENTER_VIEW_LOGS',
  'EMAIL_CENTER_VIEW_INBOUND',
  'EMAIL_CENTER_SEND_TEST',
  'EMAIL_CENTER_VIEW_PERSONAL_DATA',
] as const;

export type EmailCenterPermission = (typeof EMAIL_CENTER_PERMISSIONS)[number];
