ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "professionalProfileId" TEXT;

ALTER TABLE "FacebookUrlImportLog" ADD COLUMN IF NOT EXISTS "found" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "FacebookUrlImportLog" ADD COLUMN IF NOT EXISTS "skipped" INTEGER NOT NULL DEFAULT 0;
